# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Fetch VNDB

on:
  schedule:
    - cron: '11 4 * * 1' # Every Monday at 4:11 AM UTC
  workflow_dispatch:
    
permissions: write-all

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download data from VNDB
        run: |
          cd ..
          wget -O vndb.tar.zst https://dl.vndb.org/dump/vndb-db-latest.tar.zst
          
      - name: install zstd
        run: sudo apt-get install zstd -y
      - name: unzip and move
        run: |
          cd ..
          zstd -d vndb.tar.zst
          tar -xvf vndb.tar
          mv db/vn* PotatoDBMapper/assets/input
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Fetch VNDB data" -a || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
